name: Deploy

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nas1010/getting-started:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push nas1010/getting-started:$GITHUB_SHA

      - name: Deploy to Staging Server
        if: github.ref == 'refs/heads/staging' # Ensure the deployment only happens on the staging branch
        run: |
          echo "Deploying to staging server"

          # SSH into your staging server and run the commands
          ssh -i ${{ secrets.DEPLOY_SSH_KEY }} <<EOF
            docker pull nas1010/getting-started:$GITHUB_SHA
            docker run -d nas1010/getting-started:$GITHUB_SHA
          EOF
