name: Deploy

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Build Docker image and tag it with the commit SHA
          docker build -t username/my-nextjs-app:$GITHUB_SHA .

          # Push Docker image to Docker Hub
          docker push username/my-nextjs-app:$GITHUB_SHA

      - name: Deploy to Server
        run: |
          # Example of deployment depending on the branch
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production"
            # Add your production deployment steps here, like SSH to server
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "Deploying to staging"
            # Add your staging deployment steps here
          fi
